### ISSUE TITLE
0.111: test suite is falling in `t/descriptive.t`

### ISSUE THREAD

**Issue by kloczek** [rjbs/Getopt-Long-Descriptive#44] opened 2023-11-20 21:47 UTC
Looks like something is wrong
```console
+ cd Getopt-Long-Descriptive-0.111
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
#
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker 6.78 7.70
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Test Requires ===
#
#     Module                    Want     Have
#     ------------------------ ----- --------
#     CPAN::Meta::Check        0.011    0.018
#     CPAN::Meta::Requirements   any    2.143
#     ExtUtils::MakeMaker        any     7.70
#     File::Spec                 any     3.88
#     Test::Fatal                any    0.017
#     Test::More                0.96 1.302196
#     Test::Warnings           0.005    0.032
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module               Want  Have
#     ------------------- ----- -----
#     Carp                  any  1.54
#     File::Basename        any  2.86
#     Getopt::Long         2.33  2.57
#     List::Util            any  1.63
#     Params::Validate     0.97  1.31
#     Scalar::Util          any  1.63
#     Sub::Exporter       0.972 0.990
#     Sub::Exporter::Util   any 0.990
#     overload              any  1.37
#     strict                any  1.12
#     warnings              any  1.65
#
t/00-report-prereqs.t .. ok

#   Failed test 'got one warning about ambiguity of options'
#   at t/descriptive.t line 465.
# warning: Getopt::Long::Descriptive was configured with these ambiguous options: f
# warning: Duplicate specification "faith|f" for option "f"
# Looks like you failed 1 test of 60.
t/descriptive.t ........
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/60 subtests
t/shortcircuit.t ....... ok
t/zzz-check-breaks.t ... ok

Test Summary Report
-------------------
t/descriptive.t      (Wstat: 256 Tests: 60 Failed: 1)
  Failed test:  59
  Non-zero exit status: 1
Files=4, Tests=74,  0 wallclock secs ( 0.03 usr  0.02 sys +  0.58 cusr  0.07 csys =  0.70 CPU)
Result: FAIL
Failed 1/4 test programs. 1/74 subtests failed.
make: *** [Makefile:862: test_dynamic] Error 255
```

**Comment by rjbs** [comment] 2023-11-21 00:25
Duplicate of https://github.com/rjbs/Getopt-Long-Descriptive/pull/43

**Closed by rjbs** 2023-11-21 00:25 UTC
